### ISSUE TITLE
 Error during retrieving taxa info from NCBI

### ISSUE THREAD

**Issue by UNIVERSALIONZ** [HobnobMancer/cazy_webscraper#127] opened 2024-03-25 06:15 UTC
Please complete this report in full and as much detail as possible. It will help with getting the bug fixed far sooner!

## Describe the bug

**The error encountered is either "_Bio.Entrez.Parser.CorruptedXMLError: Failed to parse the XML data (not well-formed (invalid token): line 23399, column 20). Please make sure that the input data are not corrupted._" .** 

## Expected behavior
The program ends automatically after 24% completion of retrieving tax info from NCBI

## Screenshots
![unnamed](https://github.com/HobnobMancer/cazy_webscraper/assets/84319878/bbd4332d-0d42-47e1-8592-f93eddf58750)

## Setup
Please provide a brief summary of your setup/computer you are using. For example:

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Laptop/Desktop

**Comment by HobnobMancer** [comment] 2024-03-25 08:24
Thanks for flagging this. This is a duplicate of issue #120, so I am closing this issue and continuing progress on existing issue

**Closed by HobnobMancer** 2024-03-25 08:24 UTC
Labels: duplicate
