### ISSUE TITLE
ModuleNotFoundError: No module named 'cazy_webscraper.cazy_webscraper‘

### ISSUE THREAD

**Issue by NaiveLittleTiger** [HobnobMancer/cazy_webscraper#69] opened 2022-01-12 15:08 UTC
## Describe the bug
I finished installing cazy-webscraper package using 'pip install cazy-webscraper', when I try to use it then get the following error,"ModuleNotFoundError: No module named 'cazy_webscraper.cazy_webscraper‘ ", Then I try to install from source code, I also get same error. I don't know the reason. Can anyone assist me? thanks!
![image](https://user-images.githubusercontent.com/38722443/149166186-dfa2f06e-0d63-477c-a0c1-f92d0ffc7506.png)

**Comment by HobnobMancer** [comment] 2022-01-12 17:43
Thanks for the bug report, they are extremely useful (especially while `cazy_webscraper` is still in beta).

The issues was the result of line 77 in the `setup.py` not having been updated to match the new program architecture.  
The line has been updated to point to the correct file name for the main entry point (it now points to `cazy_scraper` instead of `cazy_webscraper`).  

This should now be fixed in the new pypi release (v2.0.2).

In future, it is good practice to fill out the bug report form in full. This facilitates the reproducibility of what caused the issue to be raised, which in turn makes finding the possible cause of the issue far easier and significantly faster. Luckily, in this case I was able to reproduce the issue; however, with the information provided arguably your work is not reproducible. The screen capture of your terminal isn't displaying the standard output for a Linux system. If you were not using a POSIX os then that could have been a cause of the problem. Additionally, with no information provided about the virtual environment you are using, the issue could have been caused by import and/or version conflicts. Without that information up front we can't rule out or rule in a lot of possibilities without a lot of backwards and forwards via comments and often a lot of extra work and playing around our end, especially if we aren't able to reproduce the issue. Long story short, provide all the info necessary for reproducing your work, which makes likes life easier for everyone.

**Closed** 2022-01-17 15:48 UTC
Labels: bug

**Comment by MagnusHallas** [comment] 2025-01-31 10:25
I think I have a similar problem.
I'm on a windows 11 computer, using anaconda prompt terminal.
I have done the conda install: conda install -c bioconda cazy_webscraper. 

I hope this print from the terminal helps you in locating the bug. Sorry if this is not enough, I'm not a python or terminal superuser.

base) C:\Windows\System32>python
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cazy_scraper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cazy_scraper'
>>> exit()

(base) C:\Windows\System32>cazy_webscraper
'cazy_webscraper' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Windows\System32>python -m cazy_webscraper -V
C:\ProgramData\anaconda3\python.exe: No module named cazy_webscraper.__main__; 'cazy_webscraper' is a package and cannot be directly executed

(base) C:\Windows\System32>python -m cazy_webscraper.cazy_scraper -V
usage: cazy_webscraper.py [-h] [--cache_dir CACHE_DIR] [--cazy_data CAZY_DATA] [--cazy_synonyms CAZY_SYNONYMS]
                          [--classes CLASSES] [-c config file] [-C] [-o DB_OUTPUT] [-d DATABASE]
                          [--delete_old_relationships] [-f] [--families FAMILIES] [--genera GENERA]
                          [--kingdoms KINGDOMS] [-l log file name] [-n] [--nodelete_cache] [--nodelete_log]
                          [-r RETRIES] [--sql_echo] [-s] [--species SPECIES] [--strains STRAINS] [-t TIMEOUT]
                          [--validate] [-v] [-V]
                          email
